### PR TITLE
Fix SP recovery when auxflash is present

### LINKED ISSUE #486: `InvalidUpdateChunk` recovery mechanism doesn't work if there's an aux flash image
#472 introduced an `InvalidUpdateChunk` recovery mechanism (originally implemented in #334). Some background context on that mechanism:

* The SP is told the total size of an update up front.
* The SP expects chunks of an update to be delivered sequentially.
    * Assuming a chunk size of `n` (the particular chunk size is not relevant to this issue), it expects to receive `MgsRequest::UpdateChunk` messages containing chunks `[0, n), [n, 2*n), [2*n, 3*n), ...` until the end of the update. (The last chunk may be shorter than `n`; that's fine and also not relevant here.)
* When the SP receives an `MgsRequest::UpdateChunk` starting at offset M, it will send back either:
    * `SpResponse::UpdateChunkAck` if it had previously received chunks covering `[0, M)`
    * `SpResponse::Error(SpError::InvalidUpdateChunk)` if it had previously received chunks covering `[0, N)` for some `N != M`
* The MGS <-> SP messaging library also has retries built-in. If MGS sends a request and doesn't receive a response within a timeout, it will resend that request.
* These two things can collide:
    1. Suppose we have successfully sent/received chunks covering `[0, M)`.
    2. MGS sends an `MgsRequest::UpdateChunk` containing `[M, M+n)`.
    3. Either the SP enqueues this request doesn't process it yet for unknown reasons (control-plane-agent busy servicing another request? some higher-priority task is starving it?) or it does process the request but the response is lost or delayed for unknown reasons. The key here is that the SP _does_ receive the correct update chunk, but MGS _does not_ get a prompt response.
    4. MGS doesn't get a response within its timeout, so resends an `MgsRequest::UpdateChunk` containing `[M, M+n)`.
    5. After step 3, the SP is expecting the next `UpdateChunk` to contain `[M+n, M+2*n)`. But it gets the resend of `[M, M+n)`, so sends back an `SpError::InvalidUpdateChunk`.
    
This is where the recovery mechanism kicks in. What's supposed to happen is:

* MGS receives an `InvalidUpdateChunk` - it goes into recovery mode
* MGS sends an `MgsRequest::UpdateStatus(component_being_updated)` to ask the SP what its view of the update's progress is
* If the SP sends back an `UpdateStatus::InProgress(status)` response, MGS does some sanity checking:
    * The update has to have the same ID (otherwise it assumes the `InvalidUpdateChunk` is because some other client has started a different update)
    * The total size of the update the SP expects has to match the size of the data we're trying to deliver
    * The update progress offset has to be in-bounds for the data we're trying to deliver
* If the sanity checks pass, MGS goes back to driving the update starting with an `UpdateChunk` beginning at whatever offset the SP reported

---

Extra background for this issue: SP images may have sort-of-independent-sort-of-not "aux flash" images. If they do have an aux flash image, there's a whole "update preparation" phase where the SP is given a hash of the aux flash, and it checks whether it locally already has that aux flash image. (aux flash images change less frequently than every release, so this check lets us skip the delivery / write of this data if it hasn't changed). The distinction between these two is a little muddy, which is strongly related to the bug(s) below.

---

During a recent customer update, we had this recovery mechanism fail in two different-but-related ways. The first was that when MGS sent the `MgsRequest::UpdateStatus(component_being_updated)` to figure out how far along things were, the SP claimed update status was not supported for that component. This was during the "deliver a new aux flash image" phase:

```
22:58:31.844Z WARN e461d5d5-085f-49b4-8c2f-70dbfc2ad7b3 (ManagementSwitch): received invalid update chunk from SP; attempting recovery
    file = /home/build/.cargo/git/checkouts/management-gateway-service-6a0a5310b2e39f6a/ea2f39c/gateway-sp-comms/src/single_sp/update.rs:680
    interface = gimlet18
    socket = control-plane-agent

22:58:31.865Z ERRO e461d5d5-085f-49b4-8c2f-70dbfc2ad7b3 (ManagementSwitch): invalid update chunk recovery failed: could not get update status from SP
    error = Error response from SP: unsupported request for this SP component
    file = /home/build/.cargo/git/checkouts/management-gateway-service-6a0a5310b2e39f6a/ea2f39c/gateway-sp-comms/src/single_sp/update.rs:770
    interface = gimlet18
    socket = control-plane-agent

22:58:31.865Z ERRO e461d5d5-085f-49b4-8c2f-70dbfc2ad7b3 (ManagementSwitch): aux flash update failed
    error = Error response from SP: invalid update chunk
    file = /home/build/.cargo/git/checkouts/management-gateway-service-6a0a5310b2e39f6a/ea2f39c/gateway-sp-comms/src/single_sp/update.rs:243
    id = 521b5098-dd10-4c2b-ae5d-9be7e2c0bd34
    interface = gimlet18
    socket = control-plane-agent
```

I believe the source of this mismatch is:

* While delivering the aux flash image, MGS is sending data [under the `SpComponent::SP_AUX_FLASH` component](https://github.com/oxidecomputer/management-gateway-service/blob/8300079d9b2d6cb0d5ab07a6ce4b0b0760e493fb/gateway-sp-comms/src/single_sp/update.rs#L232).
* That component is passed into its [invalid update recovery function](https://github.com/oxidecomputer/management-gateway-service/blob/8300079d9b2d6cb0d5ab07a6ce4b0b0760e493fb/gateway-sp-comms/src/single_sp/update.rs#L749).
* However, the SP implementation has comment noting that it [expects clients to only ever ask for `SpComponent::SP_ITSELF` status, not `SpComponent::SP_AUX_FLASH`](https://github.com/oxidecomputer/hubris/blob/e105132ac67b0110befbaa93d6f6e2772d7163cd/task/control-plane-agent/src/mgs_compute_sled.rs#L666-L673), so it sends back an "unsupported request for this SP component" when MGS asks for the aux flash update status.

The second failure was after we'd successfully delivered the aux flash and attempted recovery on the SP image:

```
23:09:41.614Z INFO e461d5d5-085f-49b4-8c2f-70dbfc2ad7b3 (ManagementSwitch): starting SP update
    aux_flash_chck = [117, 212, 28, 108, 121, 92, 114, 76, 229, 29, 34, 9, 228, 96, 216, 167, 66, 247, 223, 190, 53, 1, 8, 198, 121, 105, 162, 147, 139, 133, 145, 28]
    aux_flash_size = 1331272
    file = /home/build/.cargo/git/checkouts/management-gateway-service-6a0a5310b2e39f6a/ea2f39c/gateway-sp-comms/src/single_sp/update.rs:156
    id = 5413864a-c28d-4cd0-ba69-c44a22cdb9d0
    interface = gimlet18
    socket = control-plane-agent
    sp_image_size = 700928
23:09:54.476Z INFO e461d5d5-085f-49b4-8c2f-70dbfc2ad7b3 (ManagementSwitch): update preparation complete
    file = /home/build/.cargo/git/checkouts/management-gateway-service-6a0a5310b2e39f6a/ea2f39c/gateway-sp-comms/src/single_sp/update.rs:208
    interface = gimlet18
    socket = control-plane-agent
    update_id = 13e5e9f4-5d27-4cc2-be73-8fb6235eee22
23:09:59.010Z INFO e461d5d5-085f-49b4-8c2f-70dbfc2ad7b3 (ManagementSwitch): aux flash update complete
    file = /home/build/.cargo/git/checkouts/management-gateway-service-6a0a5310b2e39f6a/ea2f39c/gateway-sp-comms/src/single_sp/update.rs:240
    id = 13e5e9f4-5d27-4cc2-be73-8fb6235eee22
    interface = gimlet18
    socket = control-plane-agent
23:10:03.172Z WARN e461d5d5-085f-49b4-8c2f-70dbfc2ad7b3 (ManagementSwitch): received invalid update chunk from SP; attempting recovery
    file = /home/build/.cargo/git/checkouts/management-gateway-service-6a0a5310b2e39f6a/ea2f39c/gateway-sp-comms/src/single_sp/update.rs:680
    interface = gimlet18
    socket = control-plane-agent
23:10:03.185Z ERRO e461d5d5-085f-49b4-8c2f-70dbfc2ad7b3 (ManagementSwitch): invalid update chunk recovery failed: SP expects an incorrect image length
    file = /home/build/.cargo/git/checkouts/management-gateway-service-6a0a5310b2e39f6a/ea2f39c/gateway-sp-comms/src/single_sp/update.rs:803
    interface = gimlet18
    our_image_len = 700928
    socket = control-plane-agent
    sp_expects_len = 2032200
23:10:03.185Z ERRO e461d5d5-085f-49b4-8c2f-70dbfc2ad7b3 (ManagementSwitch): update failed
    error = Error response from SP: invalid update chunk
    file = /home/build/.cargo/git/checkouts/management-gateway-service-6a0a5310b2e39f6a/ea2f39c/gateway-sp-comms/src/single_sp/update.rs:268
    id = 13e5e9f4-5d27-4cc2-be73-8fb6235eee22
    interface = gimlet18
    socket = control-plane-agent
```

This time, recovery failed because the SP reported that it expected the length `2032200`, which failed our "does the SP expect the amount of data we're trying to send" sanity check, because the length of the SP image was only `700928`. The SP's claim it was expecting `2032200` is because it _added together_ both the aux flash image size (`1331272`) and the SP image size (`700928`); but MGS is trying to treat those as largely-independent.

I'm not sure which side is in the wrong here; my gut feeling is the SP side is mixing the two image kinds together a little more than it should and this is mostly a hubris-side issue. But we could probably paper over this on the MGS side pretty easily? (I think that would be roughly: always ask for `SP_ITSELF` status, never `SP_AUX_FLASH`, and expect the total length to be the sum of the two sizes. Would need to double check whether the SP _offset_ that comes back is in terms of the total size or just the "size within whichever image is being delivered", but the fact that I have to ask that question at all is why I feel like this may be more of a "we should split these out more cleanly" thing.)

### PR DESCRIPTION
**Pull request by mkeeter**
Fixes #486 (see that issue's excellent writeup for additional context)

This PR allows component updates to fine-tune how they handle `UpdateStatus` during recovery.

Specifically, they can override the component for which they request update status, then apply offsets to both the byte position and the total image size.  For most components, this isn't necessary, but it's critical for the combined SP + auxflash image: we must request `SP_ITSELF` as the `UpdateStatus` target component (even when updating the auxflash), and compensate for the other image size when interpreting the results.

I tested this by adding fault injection to the SP firmware, causing it to drop 5% of packets:
```diff
diff --git a/task/control-plane-agent/src/main.rs b/task/control-plane-agent/src/main.rs
index bfb414e2b3..16ba76a6e2 100644
--- a/task/control-plane-agent/src/main.rs
+++ b/task/control-plane-agent/src/main.rs
@@ -607,8 +607,11 @@
             mgs_handler,
             self.tx_buf,
         ) {
-            meta.size = n as u32;
-            self.packet_to_send = Some(meta);
+            // XXX drop 5% of outgoing packets
+            if userlib::sys_get_timer().now % 20 != 0 {
+                meta.size = n as u32;
+                self.packet_to_send = Some(meta);
+            }
         }
     }
 }
```

Doing a `faux-mgs` update without this patch, I reproduce the behavior in #486.

With this patch in place, I see that recovery is happening.  Here's a console log when updating both the auxflash and SP image (adding a small random blob to auxflash to force an update):
```console
$ cargo run -pfaux-mgs -- --interface=en9 update sp 0 $HUMILITY_ARCHIVE
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/faux-mgs --interface=en9 update sp 0 /Users/mjk/oxide/hubris/target/grapefruit-a/dist/default/build-grapefruit-a-image-default.zip`
Apr 21 10:29:14.593 INFO creating SP handle on interface en9, component: faux-mgs
Apr 21 10:29:14.595 INFO generated update ID, id: 43775c4e-0743-4811-8a8e-b34f5c4ac298, component: faux-mgs
Apr 21 10:29:14.596 INFO initial discovery complete, addr: [fe80::c1d:8cff:fec0:e207%28]:11111, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:29:14.643 INFO starting SP update, sp_image_size: 557312, aux_flash_size: 354532, aux_flash_chck: [7, 36, 42, 96, 148, 52, 210, 110, 42, 228, 24, 187, 16, 15, 192, 239, 201, 150, 9, 172, 106, 148, 70, 202, 145, 182, 219, 146, 109, 191, 9, 20], id: 43775c4e-0743-4811-8a8e-b34f5c4ac298, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:29:19.422 WARN ignoring unexpected RPC response, message: Message { header: Header { version: 25, message_id: 3 }, kind: SpResponse(Error(UpdateInProgress(Preparing(UpdatePreparationStatus { id: UpdateId([67, 119, 92, 78, 7, 67, 72, 17, 138, 142, 179, 79, 92, 74, 194, 152]), progress: Some(UpdatePreparationProgress { current: 0, total: 48 }) })))) }, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:29:19.423 WARN ignoring unexpected RPC response, message: Message { header: Header { version: 25, message_id: 3 }, kind: SpResponse(Error(UpdateInProgress(Preparing(UpdatePreparationStatus { id: UpdateId([67, 119, 92, 78, 7, 67, 72, 17, 138, 142, 179, 79, 92, 74, 194, 152]), progress: Some(UpdatePreparationProgress { current: 0, total: 48 }) })))) }, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:29:21.607 INFO update preparing: 22/48, component: faux-mgs
Apr 21 10:29:22.638 INFO update preparing: 29/48, component: faux-mgs
Apr 21 10:29:23.671 INFO update preparing: 36/48, component: faux-mgs
Apr 21 10:29:24.714 INFO update preparing: 43/48, component: faux-mgs
Apr 21 10:29:25.717 INFO aux flash scan complete, total_size: 911844, found_match: false, component: faux-mgs
Apr 21 10:29:25.821 INFO update preparation complete, update_id: 43775c4e-0743-4811-8a8e-b34f5c4ac298, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:29:29.870 WARN received invalid update chunk from SP; attempting recovery, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:29:29.871 INFO update in progress, total_size: 911844, bytes_received: 18582, component: faux-mgs
Apr 21 10:29:29.872 WARN invalid update chunk recovery: attempting to resume from offset 18582, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:29:31.929 WARN received invalid update chunk from SP; attempting recovery, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:29:31.930 INFO update in progress, total_size: 911844, bytes_received: 41076, component: faux-mgs
Apr 21 10:29:31.930 WARN invalid update chunk recovery: attempting to resume from offset 41076, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:29:33.950 WARN received invalid update chunk from SP; attempting recovery, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:29:33.950 INFO update in progress, total_size: 911844, bytes_received: 47922, component: faux-mgs
Apr 21 10:29:33.951 WARN invalid update chunk recovery: attempting to resume from offset 47922, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:29:35.969 WARN received invalid update chunk from SP; attempting recovery, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:29:35.970 INFO update in progress, total_size: 911844, bytes_received: 54768, component: faux-mgs
Apr 21 10:29:35.970 WARN invalid update chunk recovery: attempting to resume from offset 54768, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:29:38.029 WARN received invalid update chunk from SP; attempting recovery, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:29:38.030 INFO update in progress, total_size: 911844, bytes_received: 76284, component: faux-mgs
Apr 21 10:29:38.031 WARN invalid update chunk recovery: attempting to resume from offset 76284, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:29:40.109 WARN received invalid update chunk from SP; attempting recovery, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:29:40.110 INFO update in progress, total_size: 911844, bytes_received: 105624, component: faux-mgs
[...etc...]
Apr 21 10:31:56.687 WARN received invalid update chunk from SP; attempting recovery, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:31:56.688 INFO update in progress, total_size: 911844, bytes_received: 878740, component: faux-mgs
Apr 21 10:31:56.689 WARN invalid update chunk recovery: attempting to resume from offset 524208, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:31:58.744 WARN received invalid update chunk from SP; attempting recovery, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:32:00.748 INFO update in progress, total_size: 911844, bytes_received: 894388, component: faux-mgs
Apr 21 10:32:00.749 WARN invalid update chunk recovery: attempting to resume from offset 539856, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:32:02.767 WARN received invalid update chunk from SP; attempting recovery, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:32:02.768 INFO update in progress, total_size: 911844, bytes_received: 899278, component: faux-mgs
Apr 21 10:32:02.769 WARN invalid update chunk recovery: attempting to resume from offset 544746, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:32:03.114 INFO update complete, id: 43775c4e-0743-4811-8a8e-b34f5c4ac298, interface: en9, socket: control-plane-agent, component: faux-mgs
update complete
```

Re-running the same update, we see that we skip the auxflash update (`found_match: true` and `bytes_received` starts above `aux_flash_size: 354532`), and recovery still works:
```console
$ cargo run -pfaux-mgs -- --interface=en9 update sp 0 $HUMILITY_ARCHIVE
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/faux-mgs --interface=en9 update sp 0 /Users/mjk/oxide/hubris/target/grapefruit-a/dist/default/build-grapefruit-a-image-default.zip`
Apr 21 10:32:59.652 INFO creating SP handle on interface en9, component: faux-mgs
Apr 21 10:32:59.654 INFO generated update ID, id: 9421eed2-19bd-4bb0-8b9c-923a54e80738, component: faux-mgs
Apr 21 10:32:59.655 INFO initial discovery complete, addr: [fe80::c1d:8cff:fec0:e207%28]:11111, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:32:59.702 INFO starting SP update, sp_image_size: 557312, aux_flash_size: 354532, aux_flash_chck: [7, 36, 42, 96, 148, 52, 210, 110, 42, 228, 24, 187, 16, 15, 192, 239, 201, 150, 9, 172, 106, 148, 70, 202, 145, 182, 219, 146, 109, 191, 9, 20], id: 9421eed2-19bd-4bb0-8b9c-923a54e80738, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:33:04.350 INFO update preparing: 0/48, component: faux-mgs
Apr 21 10:33:04.350 WARN ignoring unexpected RPC response, message: Message { header: Header { version: 25, message_id: 5 }, kind: SpResponse(UpdateStatus(Preparing(UpdatePreparationStatus { id: UpdateId([148, 33, 238, 210, 25, 189, 75, 176, 139, 156, 146, 58, 84, 232, 7, 56]), progress: Some(UpdatePreparationProgress { current: 0, total: 48 }) }))) }, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:33:04.350 WARN ignoring unexpected RPC response, message: Message { header: Header { version: 25, message_id: 5 }, kind: SpResponse(UpdateStatus(Preparing(UpdatePreparationStatus { id: UpdateId([148, 33, 238, 210, 25, 189, 75, 176, 139, 156, 146, 58, 84, 232, 7, 56]), progress: Some(UpdatePreparationProgress { current: 0, total: 48 }) }))) }, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:33:05.353 INFO aux flash scan complete, total_size: 911844, found_match: true, component: faux-mgs
Apr 21 10:33:06.351 INFO update preparation complete, update_id: 9421eed2-19bd-4bb0-8b9c-923a54e80738, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:33:06.356 INFO update in progress, total_size: 911844, bytes_received: 356488, component: faux-mgs
Apr 21 10:33:10.369 WARN received invalid update chunk from SP; attempting recovery, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:33:10.370 INFO update in progress, total_size: 911844, bytes_received: 359422, component: faux-mgs
Apr 21 10:33:10.370 WARN invalid update chunk recovery: attempting to resume from offset 4890, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:33:14.429 WARN received invalid update chunk from SP; attempting recovery, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:33:14.430 INFO update in progress, total_size: 911844, bytes_received: 375070, component: faux-mgs
Apr 21 10:33:14.430 WARN invalid update chunk recovery: attempting to resume from offset 20538, interface: en9, socket: control-plane-agent, component: faux-mgs
[...snip...]
Apr 21 10:35:04.286 INFO update in progress, total_size: 911844, bytes_received: 908080, component: faux-mgs
Apr 21 10:35:04.286 WARN invalid update chunk recovery: attempting to resume from offset 553548, interface: en9, socket: control-plane-agent, component: faux-mgs
Apr 21 10:35:04.596 INFO update complete, id: 9421eed2-19bd-4bb0-8b9c-923a54e80738, interface: en9, socket: control-plane-agent, component: faux-mgs
update complete
```

Running `humility flash --check` confirms that the image is correct:
```console
$ humility flash --check
humility: attached to archive
humility: attaching with chip set to "STM32H753ZITx"
humility: attached via ST-Link V3
humility: verified 544.25KB in 23 seconds
humility: verified auxflash in slot 2
```

### CODE REVIEW

File: gateway-sp-comms/src/single_sp/update.rs [hunk 1]
```diff
@@ -256,6 +262,11 @@ async fn drive_sp_update(
         SpComponent::SP_ITSELF,
         update_id,
         sp_image,
+        UpdateStatusParams {
+            component: SpComponent::SP_ITSELF,
+            bytes_received_offset: auxflash_size,
+            total_size_delta: auxflash_size,
```
Comment (jgallagher) [inline gateway-sp-comms/src/single_sp/update.rs]: I'm not sure this is a good suggestion, but: `UpdateStatusParams` is pretty generic, but in practice it only ever has two possible values: `(SP_ITSELF, 0, sp_len)` and `(SP_ITSELF, aux_len, aux_len)`. Would it be clearer to make it an enum? Something like

```rust
enum UpdateStatusParams {
    AuxFlashBeforeSp { sp_len: usize },
    SpAfterAuxFlash { auxflash_len: usize },
}
```

There's no reasonable default value for that, though, so all the functions that currently take a non-optional `UpdateStatusParams` would have to take `Option<UpdateStatusParams>`. Or we could add a third variant for "normal update" and use that as the default value.

File: gateway-sp-comms/src/single_sp/update.rs [hunk 2]
```diff
@@ -738,6 +770,33 @@ async fn send_single_update_chunk(
...
 }
 
+/// Parameters to be used when requesting [`UpdateStatus`]
+#[derive(Copy, Clone, Debug)]
+pub(crate) struct UpdateStatusParams {
+    /// Component for which status should be requested
+    ///
+    /// This is usually the component being updated, with one exception: if
+    /// we're updating the SP's auxflash, we request the status for the
+    /// [`SP_ITSELF`] component, which returns monotonic progress for the
```
Comment (jgallagher) [inline gateway-sp-comms/src/single_sp/update.rs]: I don't think this rustdoc link works as-is; either needs to be

```suggestion
    /// [`SpComponent::SP_ITSELF`] component, which returns monotonic progress for the
```

or make it a bare `SP_ITSELF`. (This may be moot pending the question about changing this to an enum.)

File: gateway-sp-comms/src/single_sp/update.rs [hunk 3]
```diff
@@ -738,6 +770,33 @@ async fn send_single_update_chunk(
...
+    /// combined auxflash and SP update.
+    component: SpComponent,
+
+    /// Value to subtract from the reported `bytes_received` value
+    ///
+    /// This is usually 0, but if we're updating the SP image and have an
+    /// auxflash image, then we must subtract the auxflash size (because the SP
+    /// image is delivered after the auxflash image, and `UpdateStatus` uses a
+    /// monotonic counter from 0 to `aux_len + sp_len`.
```
Comment (jgallagher) [inline gateway-sp-comms/src/single_sp/update.rs]:
```suggestion
    /// monotonic counter from 0 to `aux_len + sp_len`).
```

File: gateway-sp-comms/src/single_sp/update.rs [hunk 4]
```diff
@@ -746,42 +805,73 @@ async fn send_single_update_chunk(
...
+    .result
+    .and_then(expect_update_status)
+    {
+        Ok(UpdateStatus::InProgress(progress)) => progress,
+        Ok(other_status) => {
+            error!(
+                log,
+                "invalid update chunk recovery failed: \
+                 SP update status is not in progress";
+                "status" => ?other_status,
```
Comment (jgallagher) [inline gateway-sp-comms/src/single_sp/update.rs]: I realize these were here before, but can we add `"id" => %update_id` to these logs?

File: gateway-sp-comms/src/single_sp/update.rs [hunk 5]
```diff
@@ -746,42 +805,73 @@ async fn send_single_update_chunk(
...
 
     let UpdateInProgressStatus { id, bytes_received, total_size } = progress;
     let id = Uuid::from(id);
 
+    // Remap our position in the update to handle combined auxflash + SP counter
+    let Some(bytes_received) = usize::try_from(bytes_received)
+        .expect("u32 fits in usize")
+        .checked_sub(params.bytes_received_offset)
+    else {
+        error!(
```
Comment (jgallagher) [inline gateway-sp-comms/src/single_sp/update.rs:873]: Two minor nits:

1. Can we add `"id" => %update_id` to these logs too?
2. These new checks should probably come after the `if id != update_id` check on line 881, right? If the SP has started a different update, we don't want to log a size math error instead.

**Review by jgallagher — COMMENTED** [review]
Thanks, this looks great. Just a few minor questions/comments.

File: gateway-sp-comms/src/single_sp/update.rs (hunk 5 above)
Comment (mkeeter) [reply gateway-sp-comms/src/single_sp/update.rs:873]: Good catch on the ordering, fixed (and I added `%update_id` to relevant logs)

File: gateway-sp-comms/src/single_sp/update.rs (hunk 4 above)
Comment (mkeeter) [reply gateway-sp-comms/src/single_sp/update.rs]: Sure, done

File: gateway-sp-comms/src/single_sp/update.rs (hunk 1 above)
Comment (mkeeter) [reply gateway-sp-comms/src/single_sp/update.rs]: I'm ambivalent.  I think the `enum` is nice to express high-level intent, but then we'd want `component()`, `bytes_received_offset()`, and `total_size_delta()` methods on the `enum` to insulate `determine_update_resume_point_via_update_status` from the specific details, which brings us back to a very similar place.  Maybe `UpdateStatusParams` should instead have builder functions (`sp_before_auxflash(..)` and `auxflash_after_sp(..)`) to capture the same intent?

Comment (jgallagher) [reply gateway-sp-comms/src/single_sp/update.rs]: Yeah, I wasn't sure either. I do like the idea of the builder functions.

**Review by jgallagher — APPROVED** [review]

File: gateway-sp-comms/src/single_sp/update.rs (hunk 1 above)
Comment (mkeeter) [reply gateway-sp-comms/src/single_sp/update.rs]: 👍🏻  I implemented the builder functions
