### PR TITLE
[faux-mgs] Bail out of update if underlying driving task fails

### LINKED ISSUE #331: faux-mgs: Add feedback from update tokio task to `main`
When `faux-mgs` is asked to run an update, it starts the update (which internally spawns a tokio task):

https://github.com/oxidecomputer/management-gateway-service/blob/f08433801acf5a3278e0a0983dc3cd66fe5487c4/faux-mgs/src/main.rs#L1791-L1793

and then goes into an infinite loop polling the SP for its update status:

https://github.com/oxidecomputer/management-gateway-service/blob/f08433801acf5a3278e0a0983dc3cd66fe5487c4/faux-mgs/src/main.rs#L1796-L1800

If the internally-spawned tokio task dies in a way that the SP is stuck waiting for the update to complete, `faux-mgs` will get stuck in this loop indefinitely: the SP is waiting for the rest of the update, but the task that would be providing it has stopped. This loop should also bail out if the update-driving task has failed.

### PR DESCRIPTION
**Pull request by jgallagher**
Need to test before merging, but I think this bit is pretty straightforward.

Fixes #331

### CODE REVIEW

File: gateway-sp-comms/src/single_sp.rs [hunk 1]
```diff
@@ -112,6 +112,16 @@ const TLV_RPC_TOTAL_ITEMS_DOS_LIMIT: u32 = 1024;
 
 type Result<T, E = CommunicationError> = std::result::Result<T, E>;
 
+#[derive(Debug, thiserror::Error)]
+pub enum UpdateDriverTaskError {
+    #[error("update prepration failed: {0}")]
```
Comment (mkeeter) [inline gateway-sp-comms/src/single_sp.rs:117]:
```suggestion
    #[error("update preparation failed: {0}")]
```

File: gateway-sp-comms/src/single_sp.rs [hunk 2]
```diff
@@ -112,6 +112,16 @@ const TLV_RPC_TOTAL_ITEMS_DOS_LIMIT: u32 = 1024;
...
+    UpdatePrepration(String),
```
Comment (mkeeter) [inline gateway-sp-comms/src/single_sp.rs:118]: oops, this too:
```suggestion
    UpdatePreparation(String),
```

File: gateway-sp-comms/src/single_sp.rs [hunk 3]
```diff
@@ -721,7 +731,8 @@ impl SingleSp {
         update_id: Uuid,
         slot: u16,
         image: Vec<u8>,
-    ) -> Result<(), UpdateError> {
+    ) -> Result<JoinHandle<Result<(), UpdateDriverTaskError>>, UpdateError>
```
Comment (mkeeter) [inline gateway-sp-comms/src/single_sp.rs:734]: The `JoinHandle` type is a bit wordy, maybe a newtype is warranted?
```rust
type UpdateTaskHandle = JoinHandle<Result<(), UpdateDriverTaskError>>;
```
(and then use this everywhere in the PR)

Comment (jgallagher) [reply gateway-sp-comms/src/single_sp.rs:734]: Yeah, fair. I also realized after writing this that `JoinHandle` provides `.abort()`, which we probably _don't_ want callers to do. Maybe warrants a legit newtype that doesn't expose that?

Comment (mkeeter) [reply gateway-sp-comms/src/single_sp.rs:734]: that would also be fine with me, I like types 😄

File: faux-mgs/src/main.rs [hunk 4]
```diff
@@ -1788,12 +1788,23 @@ async fn update(
...
     let sp_update_id = UpdateId::from(update_id);
     loop {
+        // Bail if the update driver task has failed.
+        if update_driver.as_ref().map_or(false, |driver| driver.is_finished()) {
+            let update_driver = update_driver.take().unwrap();
+            update_driver
+                .await
+                .context("update driver task died")?
+                .context("update driver task failed")?;
+        }
```
[the remark this answers is not in the document]
Comment (jgallagher) [reply faux-mgs/src/main.rs:1806]: I don't think so, because then we could break out and assume the update is complete because we say so without getting a "final" update status from the SP.

It should be impossible for the next SP status to be anything other than "complete" if the update driving task returns `Ok(())` (since that means _it_ got confirmation from the SP that the update was done). I could add some logic to only call status 1 final time after the driver task reports completion?

[the remark this answers is not in the document]
Comment (mkeeter) [reply faux-mgs/src/main.rs:1806]: Okay, I now believe it's fine as-is!  If we had any errors in the task, then we'd bail out with an error, so it's fine to keep the loop running to finish up cleanly.

File: gateway-sp-comms/src/single_sp.rs (hunk 3 above)
Comment (jgallagher) [reply gateway-sp-comms/src/single_sp.rs]: Newtyped in [4d41c82](https://github.com/oxidecomputer/management-gateway-service/pull/333/commits/4d41c8263ba70e2144dd978f9bfd8325eb98a42d)

**Comment by jgallagher** [comment]
Ok, I was able to test this by forcing faux-mgs itself to drop some packets from the SP:

```diff
--- a/gateway-sp-comms/src/shared_socket.rs
+++ b/gateway-sp-comms/src/shared_socket.rs
@@ -464,6 +464,7 @@ struct RecvHandler<T> {

 impl<T: HostPhase2Provider> RecvHandler<T> {
     async fn run(self) {
+        let start = std::time::Instant::now();
         let mut buf = [0; gateway_messages::MAX_SERIALIZED_SIZE];
         loop {
             let (n, peer) = match self.socket.recv_from(&mut buf).await {
@@ -531,6 +532,18 @@ impl<T: HostPhase2Provider> RecvHandler<T> {
                 }
             };

+            if matches!(
+                kind,
+                MessageKind::SpResponse(SpResponse::UpdateChunkAck)
+            ) {
+                let elapsed = start.elapsed();
+                if elapsed.subsec_millis() < 10 {
+                    error!(self.log, "injecting fake packet loss from SP");
+                    continue;
+                }
+            }
+
+
             let message = Message { header, kind };
             if let Err(err) =
                 self.handle_message(&message, trailing_data, peer).await
```

If I run with that patch on `main`, I get the infinite loop as in #331 

```
Jan 17 14:41:32.681 INFO creating SP handle on interface london_sw1tp0, component: faux-mgs
Jan 17 14:41:32.712 INFO initial discovery complete, addr: [fe80::aa40:25ff:fe04:30a%10]:11111, interface: london_sw1tp0, component: faux-mgs
Jan 17 14:41:32.717 INFO generated update ID, id: 91a6adde-3d13-4fba-a495-f72a1a420d71, component: faux-mgs
Jan 17 14:41:32.784 INFO starting SP update, sp_image_size: 664320, aux_flash_size: 0, aux_flash_chck: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], id: 91a6adde-3d13-4fba-a495-f72a1a420d71, interface: london_sw1tp0, component: faux-mgs
Jan 17 14:41:41.761 INFO update in progress, total_size: 664320, bytes_received: 0, component: faux-mgs
Jan 17 14:41:41.769 INFO update preparation complete, update_id: 91a6adde-3d13-4fba-a495-f72a1a420d71, interface: london_sw1tp0, component: faux-mgs
Jan 17 14:41:43.973 INFO update in progress, total_size: 664320, bytes_received: 1956, component: faux-mgs
Jan 17 14:41:44.680 ERRO injecting fake packet loss from SP, component: faux-mgs
Jan 17 14:41:46.714 ERRO update failed, error: Error response from SP: invalid update chunk, id: 91a6adde-3d13-4fba-a495-f72a1a420d71, interface: london_sw1tp0, component: faux-mgs
Jan 17 14:41:46.755 INFO update in progress, total_size: 664320, bytes_received: 128118, component: faux-mgs
Jan 17 14:41:47.771 INFO update in progress, total_size: 664320, bytes_received: 128118, component: faux-mgs
Jan 17 14:41:48.773 INFO update in progress, total_size: 664320, bytes_received: 128118, component: faux-mgs
Jan 17 14:41:49.775 INFO update in progress, total_size: 664320, bytes_received: 128118, component: faux-mgs
Jan 17 14:41:50.777 INFO update in progress, total_size: 664320, bytes_received: 128118, component: faux-mgs
Jan 17 14:41:51.779 INFO update in progress, total_size: 664320, bytes_received: 128118, component: faux-mgs
Jan 17 14:41:52.781 INFO update in progress, total_size: 664320, bytes_received: 128118, component: faux-mgs
Jan 17 14:41:53.783 INFO update in progress, total_size: 664320, bytes_received: 128118, component: faux-mgs
Jan 17 14:41:54.785 INFO update in progress, total_size: 664320, bytes_received: 128118, component: faux-mgs
```

But running on this branch, we fail:

```
Jan 17 14:57:35.785 INFO creating SP handle on interface london_sw1tp0, component: faux-mgs
Jan 17 14:57:35.816 INFO initial discovery complete, addr: [fe80::aa40:25ff:fe04:30a%10]:11111, interface: london_sw1tp0, component: faux-mgs
Jan 17 14:57:35.821 INFO generated update ID, id: ed02a534-d044-4325-9cd2-3f03fd2f214d, component: faux-mgs
Jan 17 14:57:35.893 INFO starting SP update, sp_image_size: 664320, aux_flash_size: 0, aux_flash_chck: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], id: ed02a534-d044-4325-9cd2-3f03fd2f214d, interface: london_sw1tp0, component: faux-mgs
Jan 17 14:57:44.598 INFO update in progress, total_size: 664320, bytes_received: 0, component: faux-mgs
Jan 17 14:57:44.635 INFO update preparation complete, update_id: ed02a534-d044-4325-9cd2-3f03fd2f214d, interface: london_sw1tp0, component: faux-mgs
Jan 17 14:57:46.924 INFO update in progress, total_size: 664320, bytes_received: 1956, component: faux-mgs
Jan 17 14:57:49.017 INFO update in progress, total_size: 664320, bytes_received: 2934, component: faux-mgs
Jan 17 14:57:49.786 ERRO injecting fake packet loss from SP, component: faux-mgs
Jan 17 14:57:51.824 ERRO update failed, error: Error response from SP: invalid update chunk, id: ed02a534-d044-4325-9cd2-3f03fd2f214d, interface: london_sw1tp0, component: faux-mgs
Jan 17 14:57:51.825 INFO update in progress, total_size: 664320, bytes_received: 176040, component: faux-mgs
Error: updating sp slot 0 to build-gimlet-image.zip failed: update driver task failed: update chunk delivery failed: Error response from SP: invalid update chunk
```

It would obviously be better to recover from this! That's what #332 covers, and we should be able to test it with the same inject-fake-packets patching.

**Review by mkeeter — APPROVED** [review]
